# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["VAGRANT_DEFAULT_PROVIDER"] = "libvirt"

Vagrant.configure("2") do |config|

    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.host = "localhost"
        libvirt.uri = "qemu:///system"
    end

    # Configure Contrail Deployer Ocata
    config.vm.define "deployer" do |vm1|
        system("if [ #{ARGV[0]} = 'up' ]; then
                ssh-keygen -f '/root/.ssh/known_hosts' -R 192.168.1.50
                fi")

        vm1.vm.box = "centos/7"
        vm1.vm.box_version = "1710.01"
        vm1.vm.hostname="contrail-deployer"
        vm1.vm.provider :libvirt do |domain|
            domain.memory = 65536
            domain.machine_virtual_size = 80
            domain.boot 'network'
            domain.boot 'hd'
            domain.cpus = 4
        end
        # Shared folders relative to the root (where Vagrantfile is found)
        config.vm.synced_folder "../../centos7-shared-folder/", "/shared-folder", nfs:true, nfs_export: true, type: "nfs"
        vm1.vm.network  :private_network,
                        :ip => "192.168.1.50",
                        :libvirt__netmask => "255.255.255.0",
                        :libvirt__network_name => "mgmtnetwork",
                        # :libvirt__forward_mode => "veryisolated",
                        :libvirt__dhcp_enabled => false,
                        :mac => "52:54:00:00:01:d0"
        vm1.vm.network  :private_network,
                        :ip => "192.168.10.50",
                        :libvirt__netmask => "255.255.255.0",
                        :libvirt__network_name => "ctldatanetwork",
                        # :libvirt__forward_mode => "veryisolated",
                        :libvirt__dhcp_enabled => false,
                        :mac => "52:54:00:00:10:d0"
        vm1.vm.provision "shell", path: "../scripts/aio.sh", env: { "config_file" => "#{ENV['config_file']}" }
    end

    # Configure Contrail Deployer for A-I-O
    config.vm.define "aio" do |vm1|
        system("if [ #{ARGV[0]} = 'up' ]; then
                ssh-keygen -f '/root/.ssh/known_hosts' -R 192.168.1.60
                fi")
        vm1.vm.box = "centos/7"
        vm1.vm.box_version = "1710.01"
        vm1.vm.hostname="aio"
        vm1.vm.provider :libvirt do |domain|
            domain.memory = 65536
            domain.machine_virtual_size = 80
            domain.boot 'network'
            domain.boot 'hd'
            domain.cpus = 4
        end
        # Shared folders relative to the root (where Vagrantfile is found)
        config.vm.synced_folder "../../centos7-shared-folder/", "/shared-folder", nfs:true, nfs_export: true, type: "nfs"
        vm1.vm.network  :private_network,
                        :ip => "192.168.1.60",
                        :libvirt__netmask => "255.255.255.0",
                        :libvirt__network_name => "mgmtnetwork",
                        # :libvirt__forward_mode => "veryisolated",
                        :libvirt__dhcp_enabled => false,
                        :mac => "52:54:00:00:01:e0"
        vm1.vm.network  :private_network,
                        :ip => "192.168.10.60",
                        :libvirt__netmask => "255.255.255.0",
                        :libvirt__network_name => "ctldatanetwork",
                        # :libvirt__forward_mode => "veryisolated",
                        :libvirt__dhcp_enabled => false,
                        :mac => "52:54:00:00:10:e0"
        vm1.vm.provision "shell", path: "../scripts/aio.sh", env: { "config_file" => "#{ENV['config_file']}" }
    end

    # Configure Centos target hosts
    (1..5).each do |i|
        config.vm.define "srvr#{i}" do |vm1|
            system("if [ #{ARGV[0]} = 'up' ]; then
                ssh-keygen -f '/root/.ssh/known_hosts' -R 192.168.1.5#{i}
                fi")
            vm1.vm.box = "centos/7"
            vm1.vm.box_version = "1710.01"
            vm1.vm.hostname="srvr#{i}"
            vm1.vm.provider :libvirt do |domain|
                domain.memory = 65536
                domain.machine_virtual_size = 80
                domain.boot 'network'
                domain.boot 'hd'
                domain.cpus = 4
            end
            # Shared folders relative to the root (where Vagrantfile is found)
            config.vm.synced_folder "../../centos7-shared-folder/", "/shared-folder", nfs:true, nfs_export: true, type: "nfs"
            vm1.vm.network  :private_network,
                            :ip => "192.168.1.5#{i}",
                            :libvirt__netmask => "255.255.255.0",
                            :libvirt__network_name => "mgmtnetwork",
                            # :libvirt__forward_mode => "veryisolated",
                            :libvirt__dhcp_enabled => false,
                            :mac => "52:54:00:00:01:d#{i}"
            vm1.vm.network  :private_network,
                            :ip => "192.168.10.5#{i}",
                            :libvirt__netmask => "255.255.255.0",
                            :libvirt__network_name => "ctldatanetwork",
                            # :libvirt__forward_mode => "veryisolated",
                            :libvirt__dhcp_enabled => false,
                            :mac => "52:54:00:00:10:d#{i}"
            vm1.vm.provision "shell", path: "../scripts/target-server.sh"
        end
    end
    # Configure Centos target hosts
    (6..9).each do |i|
        config.vm.define "srvr#{i}" do |vm1|
            system("if [ #{ARGV[0]} = 'up' ]; then
                ssh-keygen -f '/root/.ssh/known_hosts' -R 192.168.1.5#{i}
                fi")
            vm1.vm.box = "centos/7"
            vm1.vm.box_version = "1710.01"
            vm1.vm.hostname="srvr#{i}"
            vm1.vm.provider :libvirt do |domain|
                domain.memory = 65536
                domain.machine_virtual_size = 80
                domain.boot 'network'
                domain.boot 'hd'
                domain.cpus = 4
            end
            # Shared folders relative to the root (where Vagrantfile is found)
            config.vm.synced_folder "../../centos7-shared-folder/", "/shared-folder", nfs:true, nfs_export: true, type: "nfs"
            vm1.vm.network  :private_network,
                            :ip => "192.168.10.5#{i}",
                            :libvirt__netmask => "255.255.255.0",
                            :libvirt__network_name => "ctldatanetwork",
                            # :libvirt__forward_mode => "veryisolated",
                            :libvirt__dhcp_enabled => false,
                            :mac => "52:54:00:00:10:d#{i}"
            vm1.vm.network  :private_network,
                            :ip => "192.168.1.5#{i}",
                            :libvirt__netmask => "255.255.255.0",
                            :libvirt__network_name => "mgmtnetwork",
                            # :libvirt__forward_mode => "veryisolated",
                            :libvirt__dhcp_enabled => false,
                            :mac => "52:54:00:00:01:d#{i}"
            vm1.vm.provision "shell", path: "../scripts/target-server.sh"
        end
    end
end
