# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["VAGRANT_DEFAULT_PROVIDER"] = "libvirt"

Vagrant.configure("2") do |config|

    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.host = "localhost"
        libvirt.uri = "qemu:///system"
    end

    # Setup target cluster servers
    (1..9).each do |i|
        config.vm.define "server#{i}" do |vm2|
            vm2.vm.box = "generic/ubuntu1604"
            vm2.vm.hostname="b2s43-vm#{i}"
            vm2.vm.provider :libvirt do |domain|
                domain.memory = 16384
                domain.cpus = 4
                domain.boot 'network'
                domain.boot 'hd'
            end
#config.vm.synced_folder "../centos7-shared-folder/", "/shared-folder", nfs:true, nfs_export: true, type: "nfs"
        config.vm.synced_folder "../centos7-shared-folder/", "/shared-folder", type: "rsync"
        vm2.vm.network  :private_network,
                        :ip => "192.168.10.7#{i}",
                        :libvirt__netmask => "255.255.255.0",
                        :libvirt__network_name => "ctldatanetwork",
                        # :libvirt__forward_mode => "veryisolated",
                        :libvirt__dhcp_enabled => false,
                        :mac => "52:54:00:00:10:d#{i}"
        vm2.vm.network  :public_network,
                        :bridge => "publicbr",
#                        :mode => "bridge",
#                        :type => "bridge",
#                        :auto_config => true,
#                        :ip => "10.84.22.7#{i}",
                        :dev => "eno1",
                        :mac => "52:54:a1:b2:01:e#{i}"
        vm2.vm.provision "shell", path: "scripts/target-server.sh"
        vm2.vm.provision "ansible" do |ansible|
            ansible.playbook="helm_cluster_playbook.yml"
        end
        end
    end
end
