# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["VAGRANT_DEFAULT_PROVIDER"] = "libvirt"
file_to_disk = './tmp/large_disk.vdi'

Vagrant.configure("2") do |config|

    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.host = "localhost"
        libvirt.uri = "qemu:///system"
    end

    # Configure Centos compute nodes 21-29
    (0..9).each do |i|
        hostnum = ( 91 + i )
        if hostnum == 100
            macnum = 10
        else
            macnum = hostnum
        end
        nodename = ( "compute" + hostnum.to_s ).to_sym
        config.vm.define nodename do |vm1|
            system("if [ #{ARGV[0]} = 'up' ]; then
                ssh-keygen -f '/root/.ssh/known_hosts' -R 192.168.10.#{hostnum}
                fi")
            vm1.vm.box = "centos/7"
            vm1.vm.hostname="compute#{hostnum}"
            vm1.vm.provider :libvirt do |domain|
                domain.storage :file, :size => '20G'
                domain.memory = 65536
                domain.machine_virtual_size = 80
                domain.boot 'network'
                domain.boot 'hd'
                domain.cpus = 4
            end
            # Shared folders relative to the root (where Vagrantfile is found)
            #config.vm.synced_folder "../centos7-shared-folder/", "/shared-folder", type:"nfs", nfs_export:true, nfs_version:3, nfs_udp:true
            vm1.vm.network  :private_network,
                            :ip => "192.168.10.#{hostnum}",
                            :libvirt__netmask => "255.255.255.0",
                            :libvirt__network_name => "ctldatanetwork",
                            # :libvirt__forward_mode => "veryisolated",
                            :libvirt__dhcp_enabled => false,
                            :mac => "52:54:69:00:10:#{macnum}"
            vm1.vm.network  :public_network,
                            :bridge => "mgmtbr",
                            :mode => "bridge",
                            :type => "bridge",
                            :auto_config => true,
                            :dev => "mgmtbr",
                            :mac => "52:54:69:22:29:#{macnum}"
            vm1.vm.provision "shell", path: "scripts/target-server.sh"
        end
    end
end
